### PR TITLE
frontend, backend: fix traceback for non-existing tasks

### LINKED ISSUE #2390: copr backend traceback
```
[2022-11-28 19:40:15,409][ ERROR][PID:350650][/usr/bin/copr-backend-process-build.managed.pid-350650][background_worker_build.py:handle_task:792] Unexpected exception
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/copr_backend/background_worker_build.py", line 786, in handle_task
    self.handle_build()
  File "/usr/lib/python3.11/site-packages/copr_backend/background_worker_build.py", line 778, in handle_build
    self._get_build_job()
  File "/usr/lib/python3.11/site-packages/copr_backend/background_worker_build.py", line 344, in _get_build_job
    self.job = BuildJob(resp.json(), self.opts)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/copr_backend/job.py", line 75, in __init__
    for key, val in task_data.items():
                    ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'
```

### PR DESCRIPTION
**Pull request by FrostyX**
Fix #2390

First, take a look at the frontend change. The
`BuildsLogic.get_srpm_build_task` never raises an exception. It returns `None` for non-existing tasks instead. The route therefore returns 200 status code even for non-existing tasks, and simply returns `nil`. I am changing this to return 404 instead.

This prompted the backend changes because exceptions started appearing.

### CODE REVIEW

**Comment by praiskup** [comment]
Would you mind bumping `MIN_FE_BE_API`?

**Comment by praiskup** [comment]
Why backend even asked for those build IDs?

**Comment by FrostyX** [comment]
> Why backend even asked for those build IDs?

I am thinking of something like 

1. User submitted a build
2. Backend added it to its priority queue
3. Because of one of the post-release bugs, the building was stuck
4. User deleted the build because it wasn't working
5. Before updating the priority queue, backend picked the build and started it

I need to check if this was the case and if this situation can happen. If yes, we should fix it.

**Comment by FrostyX** [comment]
> I am thinking of something like

Now it looks more like an issue caused by #2398.

**Comment by praiskup** [comment]
So are we going to skip this PR then?

**Comment by FrostyX** [comment]
We should probably skip this for the next mini-release. But the change is valid, I think.

File: backend/copr_backend/frontend.py [hunk 1]
```diff
@@ -8,7 +8,8 @@
 from copr_common.request import SafeRequest, RequestError
 from copr_backend.exceptions import FrontendClientException
 
-MIN_FE_BE_API = 4
+# The frontend counterpart is in `backend_general:send_frontend_version`
+MIN_FE_BE_API = 5
```
Comment (praiskup) [inline backend/copr_backend/frontend.py:12]: Further reading this code, I think I was wrong and this bump is not needed?  The frontend/backend changes in this PR are independent, right?

Anyways, the documentation here is very nice, having it (as a separate commit) woudl be nice.

File: frontend/coprs_frontend/coprs/views/backend_ns/backend_general.py [hunk 2]
```diff
@@ -348,13 +349,13 @@ def _stream():
 @backend_ns.route("/get-build-task/<task_id>/")
 @backend_ns.route("/get-build-task/<task_id>")
 def get_build_task(task_id):
-    try:
-        task = BuildsLogic.get_build_task(task_id)
-    except MalformedArgumentException:
```
Comment (praiskup) [inline frontend/coprs_frontend/coprs/views/backend_ns/backend_general.py:353]: We are actually handling the same problem, and raising this exception inside `BuildsLogic.get_build_task`.  I'd prefer to handling the problem with just one method.  Perhaps we'd just change [first()](https://github.com/fedora-copr/copr/blob/5f30af8106c226823fb25eb447506b829c3d18d2/frontend/coprs_frontend/coprs/logic/builds_logic.py#L390) call to `one()`?  Then we should get the `NoResultFound` and it would be handled on line 357 here.

**Comment by praiskup** [comment]
Thank you for this patch, it makes the code more robust..

File: backend/copr_backend/frontend.py (hunk 1 above)
Comment (FrostyX) [reply backend/copr_backend/frontend.py:12]: I think doing the `MIN_FE_BE_API` bump is a good idea because, at this moment, the backend can't handle a non-200 response. If we start returning 404 and 500 status codes from frontend, the `FrontendClient` will start raising exceptions. At the same time `_get_build_job` doesn't expect them and checks for `if resp.status_code != 200:` instead. I think we need both frontend and backend changes at the same time.

File: frontend/coprs_frontend/coprs/views/backend_ns/backend_general.py (hunk 2 above)
Comment (FrostyX) [reply frontend/coprs_frontend/coprs/views/backend_ns/backend_general.py:351]: Makes sense, I updated the PR, WDYT?
The change is in a separate commit for easier review.

**Review by praiskup — APPROVED** [review]
